DELIMITER //

CREATE PROCEDURE CFB_SUBMIT_PICK (
	IN USR INT,
    IN GM INT,
    IN SELECTED_TEAM VARCHAR(25)
)

BEGIN
	UPDATE PICKS AS P
    SET P.TEAM_ID = SELECTED_TEAM
    WHERE P.USER_ID = USR
    AND P.GAME_ID = GM
    AND LOWER(P.LEAGUE) = 'cfb';
END//

DELIMITER ;