DELIMITER //

CREATE PROCEDURE CFB_GET_USER (
	IN USERNAME_INPUT VARCHAR(50),
    IN PW_INPUT VARCHAR(64),
    OUT USER_ID INT
)

BEGIN
	SELECT U.USER_ID FROM USERS AS U
    WHERE U.USER_ID = USERNAME_INPUT
		AND U.PW = PW_INPUT;
END//

DELIMITER ;