
CREATE VIEW CFB_GET_ALL_DATA_VW AS  

SELECT  
	P.USER_ID,  
    U.USERNAME,     
    P.GAME_ID,     
    P.TEAM_ID AS TEAM_PICKED,          
    
    G.AWAY_TEAM,     
    AWAY.NAME AS AWAY_TEAM_NAME,     
    AWAY.MASCOT AS AWAY_TEAM_MASCOT,     
    AWAY.LOGO_URL AS AWAY_LOGO_URL,     
    AWAY.CONFERENCE_NAME AS AWAY_CONFERENCE,     
    AWAY.CONFERENCE_WINS AS AWAY_CONFERENCE_WINS,     
    AWAY.CONFERENCE_LOSSES AS AWAY_CONFERENCE_LOSSES,     
    AWAY.CONFERENCE_TIES AS AWAY_CONFERENCE_TIES,     
    AWAY.OVERALL_WINS AS AWAY_OVERALL_WINS,     
    AWAY.OVERALL_LOSSES AS AWAY_OVERALL_LOSSES,     
    AWAY.OVERALL_TIES AS AWAY_OVERALL_TIES,          
    
    G.HOME_TEAM,     
    HOME.NAME AS HOME_TEAM_NAME,     
    HOME.MASCOT AS HOME_TEAM_MASCOT,     
    HOME.LOGO_URL AS HOME_LOGO_URL,     
    HOME.CONFERENCE_NAME AS HOME_CONFERENCE,     
    HOME.CONFERENCE_WINS AS HOME_CONFERENCE_WINS,     
    HOME.CONFERENCE_LOSSES AS HOME_CONFERENCE_LOSSES,     
    HOME.CONFERENCE_TIES AS HOME_CONFERENCE_TIES,     
    HOME.OVERALL_WINS AS HOME_OVERALL_WINS,     
    HOME.OVERALL_LOSSES AS HOME_OVERALL_LOSSES,     
    HOME.OVERALL_TIES AS HOME_OVERALL_TIES,          
    
    L.STADIUM,     
    L.STADIUM_CAPACITY,     
    L.CITY,     
    L.STATE,          
    G.TV_COVERAGE,     
    G.BETTING_LINE,     
    G.BETTING_LINE_OVER_UNDER,     
    
    G.ATTENDANCE,     
    G.AWAY_WIN_PCT,     
    G.HOME_WIN_PCT,     
    
    G.AWAY_QUARTER1,     
    G.AWAY_QUARTER2,     
    G.AWAY_QUARTER3,     
    G.AWAY_QUARTER4,     
    G.AWAY_OVERTIME,     
    G.AWAY_TOTAL,     
    
    G.HOME_QUARTER1,     
    G.HOME_QUARTER2,     
    G.HOME_QUARTER3,     
    G.HOME_QUARTER4,     
    G.HOME_OVERTIME,     
    G.HOME_TOTAL,          
    
    G.GAME_TIME,     
    G.GAME_DATE,     
    G.GAME_MONTH,     
    G.GAME_DAY,     
    G.GAME_YEAR 
    
FROM  
	PICKS AS P   
		INNER JOIN USERS AS U    
			ON P.USER_ID = U.USER_ID   
		LEFT JOIN GAMES AS G    
			ON P.GAME_ID = G.GAME_ID   
		LEFT JOIN TEAMS AS AWAY    
			ON G.AWAY_TEAM = AWAY.TEAM_ID   
		LEFT JOIN TEAMS AS HOME    
			ON G.HOME_TEAM = HOME.TEAM_ID   
		LEFT JOIN LOCATIONS AS L    
			ON G.LOCATION = L.LOCATION_ID             
            AND G.LEAGUE = L.LEAGUE 
WHERE  
	LOWER(P.LEAGUE) = 'cfb';
    
    