CREATE PROCEDURE CREATE_DB()
BEGIN


	/*******************************************************
	CREATE TABLES 
	*******************************************************/
	CREATE TABLE IF NOT EXISTS GAMES (
		GAME_ID						INT				NOT NULL,
		LEAGUE						VARCHAR(5)		NOT NULL,
		AWAY_TEAM					VARCHAR(25)		NULL,
		HOME_TEAM					VARCHAR(25)		NULL,
		LOCATION					SMALLINT		NULL,
		TV_COVERAGE					VARCHAR(25)		NULL,
		BETTING_LINE				VARCHAR(25)		NULL,
		BETTING_LINE_OVER_UNDER		VARCHAR(25)		NULL,
		ATTENDANCE					MEDIUMINT		NULL,
		AWAY_WIN_PCT				VARCHAR(25)		NULL,
		HOME_WIN_PCT				VARCHAR(25)		NULL,
		AWAY_QUARTER1				VARCHAR(25)		NULL,
		AWAY_QUARTER2				VARCHAR(25)		NULL,
		AWAY_QUARTER3				VARCHAR(25)		NULL,
		AWAY_QUARTER4				VARCHAR(25)		NULL,
		AWAY_VERTIME				VARCHAR(25)		NULL,
		AWAY_TOTAL					VARCHAR(25)		NULL,
		HOME_QUARTER1				VARCHAR(25)		NULL,
		HOME_QUARTER2				VARCHAR(25)		NULL,
		HOME_QUARTER3				VARCHAR(25)		NULL,
		HOME_QUARTER4				VARCHAR(25)		NULL,
		HOME_OVERTIME				VARCHAR(25)		NULL,
		HOME_TOTAL					VARCHAR(25)		NULL,
		GAME_TIME					VARCHAR(25)		NULL,
		GAME_DATE					VARCHAR(25)		NULL,
		GAME_MONTH					BIT				NULL,
		GAME_DAY					BIT				NULL,
		GAME_YEAR					BIT				NULL
	);

	CREATE TABLE IF NOT EXISTS TEAMS (
		TEAM_ID						VARCHAR(25)		NOT NULL,
		LEAGUE						VARCHAR(5)		NOT NULL,
		NAME						VARCHAR(50)		NOT NULL,
		MASCOT						VARCHAR(50)		NOT NULL,
		LOGO_URL					VARCHAR(75)		NULL,
		CONFERENCE_NAME				VARCHAR(50)		NULL,
		CONFERENCE_WINS				TINYINT			NULL,
		CONFERENCE_LOSSES			TINYINT			NULL,
		CONFERENCE_TIES				TINYINT			NULL,
		OVERALL_WINS				TINYINT			NULL,
		OVERALL_LOSSES				TINYINT			NULL,
		OVERALL_TIES				TINYINT			NULL
	);

	CREATE TABLE IF NOT EXISTS LOCATIONS (
		LEAGUE						VARCHAR(5)		NOT NULL,
		LOCATION_ID					SMALLINT		NOT NULL,
		STADIUM						VARCHAR(5)		NOT NULL,
		STADIUM_CAPACITY			VARCHAR(5)		NULL,
		CITY						VARCHAR(5)		NULL,
		STATE						VARCHAR(5)		NULL,
		LATITUDE					VARCHAR(5)		NULL,
		LONGITUDE					VARCHAR(5)		NULL
	);

	CREATE TABLE IF NOT EXISTS USERS (
		USER_ID						INT				NOT NULL		AUTO_INCREMENT,
		USERNAME					VARCHAR(50)		NOT NULL,
		PW							VARCHAR(64)		NOT NULL,
		EMAIL_ADDRESS				VARCHAR(100)	NULL,
        PRIMARY KEY (USER_ID)
	);

	CREATE TABLE IF NOT EXISTS PICKS (
		USER_ID						INT				NOT NULL,
		GAME_ID						INT				NOT NULL,
		LEAGUE						VARCHAR(5)		NOT NULL,
		TEAM_ID						VARCHAR(25)		NULL
	);


	/*******************************************************
	CREATE PRIMARY KEYS
	*******************************************************/
	ALTER TABLE GAMES
		ADD CONSTRAINT PK_GAMES PRIMARY KEY (GAME_ID, LEAGUE);
	ALTER TABLE TEAMS
		ADD CONSTRAINT PK_TEAMS PRIMARY KEY (TEAM_ID, LEAGUE);
	ALTER TABLE LOCATIONS
		ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (LEAGUE, LOCATION_ID);
	-- ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_ID);
	ALTER TABLE PICKS
		ADD CONSTRAINT PK_PICKS PRIMARY KEY (USER_ID, GAME_ID, LEAGUE);


	/*******************************************************
	CREATE FOREIGN KEYS
	*******************************************************/
	ALTER TABLE GAMES
		ADD CONSTRAINT FK_GameAwayTeam
		FOREIGN KEY (AWAY_TEAM) REFERENCES TEAMS(TEAM_ID);
	ALTER TABLE GAMES
		ADD CONSTRAINT FK_GameHomeTeam
		FOREIGN KEY (HOME_TEAM) REFERENCES TEAMS(TEAM_ID);
	ALTER TABLE GAMES
		ADD CONSTRAINT FK_GameLocations
		FOREIGN KEY (LEAGUE, LOCATION) REFERENCES LOCATIONS(LEAGUE, LOCATION_ID);

	ALTER TABLE PICKS
		ADD CONSTRAINT FK_PickUser
		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);


END